### ISSUE TITLE
[BUG] MySQL Exception 

### ISSUE THREAD

**Issue by jovicdev97** [M-archand/SharpTimer-WallLists#2]
**Describe the bug**
Starting the server I'll get a traceback.

**To Reproduce**
Install Plugin
Start Server
Edit Config
Check Console

**Logs (Optional)**
`2:37
00:52:37 [EROR] (plugin:SharpTimer Map Top List) Failed to retrieve top players: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RankedPlayers AS (
SELECT
SteamID,
PlayerName,
FormattedT' at line 1
MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RankedPlayers AS (
SELECT
SteamID,
PlayerName,
FormattedT' at line 1
at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 885
at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 482
at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 357
at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 350
at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
at SharpTimerMapList.PluginSharpTimerMapList.GetTopPlayersAsync(Int32 topCount, String mapName) in C:\Users\alexr\Desktop\SharpTimer-MapList\SharpTimer-MapList.cs:line 474`

**Comment by M-archand** [comment]
@jovicdev97 please try the [new release](https://github.com/M-archand/SharpTimer-WallLists/releases), thanks

**Comment by jovicdev97** [comment]
thank you! @M-archand
